# Generated by Django 2.2.2 on 2021-02-27 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeType',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='title',
            new_name='name',
        ),
    ]
