# Generated by Django 2.0 on 2020-05-21 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20200512_2215'),
        ('carts', '0002_auto_20200512_1726'),
    ]

    operations = [
    ]
