# Generated by Django 2.2.2 on 2021-02-24 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20210223_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='fk_storewise_order',
        ),
    ]
