# Generated by Django 2.2.2 on 2021-02-27 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_visit'),
        ('carts', '0003_remove_cartitem_fk_storewise_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='fk_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Visit'),
        ),
    ]
