# Generated by Django 2.2.2 on 2021-02-28 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_variationbatch_use_batch'),
        ('carts', '0004_cart_fk_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='item',
        ),
        migrations.AddField(
            model_name='cart',
            name='cartitems',
            field=models.ManyToManyField(through='carts.CartItem', to='products.VariationBatch'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='fk_variation_batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.VariationBatch'),
        ),
    ]
