# Generated by Django 2.2.2 on 2020-06-02 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_cart_fk_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='fk_delivery_user',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='fk_ordered_store',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='fk_payment_method',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='is_delivered',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='is_paid',
        ),
    ]
