# Generated by Django 2.2.2 on 2021-03-04 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_auto_20210228_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='fk_delivery_user_id',
        ),
    ]
