# Generated by Django 2.2.2 on 2021-03-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_cart_fk_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_return',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
