# Generated by Django 2.2.2 on 2020-07-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_cartitem_fk_storewise_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='ordered_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='orginal_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
    ]
