# Generated by Django 2.2.2 on 2020-07-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_auto_20200717_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
    ]
