# Generated by Django 2.2.2 on 2020-07-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0009_cartitem_tax_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_auto_order',
            field=models.BooleanField(default=False),
        ),
    ]
