# Generated by Django 2.2.2 on 2021-03-12 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('carts', '0009_auto_20210312_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='fk_payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.PaymentMethod'),
        ),
    ]
