# Generated by Django 2.2.2 on 2020-12-31 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_can_sell_everywhere'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carts', '0010_cart_is_auto_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVariationQuantityHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_taken', models.PositiveIntegerField(default=0)),
                ('num_returned', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Variation')),
            ],
        ),
    ]
