# Generated by Django 2.2.2 on 2021-03-28 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0002_fiscalyear'),
        ('carts', '0012_auto_20210319_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='fk_fiscalyear',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_settings.FiscalYear'),
        ),
    ]
