# Generated by Django 2.2.2 on 2021-01-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0012_delete_uservariationquantityhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=50, null=True),
        ),
    ]
