# Generated by Django 2.2.2 on 2021-03-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0013_cart_fk_fiscalyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='bill_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
