# Generated by Django 2.2.2 on 2021-01-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0013_cart_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='debit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=25, null=True),
        ),
    ]
