# Generated by Django 2.2.2 on 2021-01-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0014_auto_20210109_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=25),
        ),
    ]
