# Generated by Django 2.2.2 on 2021-01-13 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carts', '0015_auto_20210112_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='fk_delivery_user_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
