# Generated by Django 2.2.2 on 2021-01-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0017_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='is_auto_order',
            field=models.IntegerField(default=0),
        ),
    ]
