# Generated by Django 2.2.2 on 2021-02-27 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210223_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_customer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fk_doctor_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors_assigned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
