# Generated by Django 2.2.2 on 2021-02-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210228_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='visit date'),
        ),
    ]
