# Generated by Django 2.2.2 on 2020-06-03 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200530_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='mobile',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+977999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,14}$')]),
        ),
    ]
