# Generated by Django 2.2.2 on 2020-07-23 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200603_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneResetOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="phone number must be entered in the format: '+97799999'. Up to 15 digits allowed", regex='^\\+?1?\\d{9,14}$')])),
                ('otp', models.CharField(blank=True, max_length=9, null=True)),
                ('count', models.IntegerField(default=0, help_text='No. of otp sent')),
                ('validated', models.BooleanField(default=False, help_text='if true, user validated otp in secount api')),
            ],
        ),
    ]
