# Generated by Django 2.2.2 on 2021-03-01 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_auto_20210227_1501'),
        ('account', '0005_visit_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='fk_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department.Department'),
        ),
    ]
