# Generated by Django 2.2.2 on 2020-07-23 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_phoneresetotp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhoneResetOTP',
            new_name='PasswordResetOTP',
        ),
    ]
