# Generated by Django 2.2.2 on 2021-03-01 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_auto_20210227_1501'),
        ('account', '0006_doctor_fk_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='fk_specialization_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_specialist', to='department.Department'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='fk_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_department', to='department.Department'),
        ),
    ]
