# Generated by Django 2.2.2 on 2021-03-01 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20210301_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='fk_specialization_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_specialist', to='specializationtype.SpecializationType'),
        ),
    ]
