# Generated by Django 2.2.2 on 2021-03-02 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_nurse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='fk_specialization_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='specializationtype.SpecializationType'),
        ),
    ]
