# Generated by Django 2.2.2 on 2021-03-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20210302_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='fk_staff_user',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='fk_store',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='fk_variation',
        ),
        migrations.DeleteModel(
            name='CustomerDepotRequest',
        ),
        migrations.DeleteModel(
            name='CustomerMessage',
        ),
        migrations.DeleteModel(
            name='CustomerRegisterSurvey',
        ),
        migrations.DeleteModel(
            name='CallLog',
        ),
    ]
