# Generated by Django 2.2.2 on 2021-03-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20210304_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='checkout_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='visit out time'),
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_status',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
