# Generated by Django 2.2.2 on 2020-08-01 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_customermessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerregistersurvey',
            old_name='name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='customerregistersurvey',
            old_name='other',
            new_name='lastname',
        ),
    ]
