# Generated by Django 2.2.2 on 2021-03-06 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20210304_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='fk_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.VisitType'),
        ),
    ]
