# Generated by Django 2.2.2 on 2020-10-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20200801_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='firebase_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
