# Generated by Django 2.2.2 on 2021-03-07 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_visit_fk_visit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['-timestamp']},
        ),
    ]
