# Generated by Django 2.2.2 on 2021-03-08 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20210307_1701'),
        ('account', '0014_auto_20210307_1942'),
    ]

    operations = [
    ]
