# Generated by Django 2.2.2 on 2021-03-08 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_merge_20210308_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='fk_customer_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_customer_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
