# Generated by Django 2.2.2 on 2021-01-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_calllog'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='is_existing',
            field=models.BooleanField(default=False),
        ),
    ]
