# Generated by Django 2.2.2 on 2021-03-12 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20210308_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='emergency_number',
            field=models.CharField(max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+977999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,14}$')]),
        ),
        migrations.AddField(
            model_name='account',
            name='fk_district',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='fk_localgov',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='fk_state',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
