# Generated by Django 2.2.2 on 2021-01-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_calllog_is_existing'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='timestamp_str',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
