# Generated by Django 2.2.2 on 2021-01-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_calllog_timestamp_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='timestamp_i64',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='timestamp_str',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
