# Generated by Django 2.2.2 on 2021-03-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20210312_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=60, null=True, unique=True, verbose_name='email'),
        ),
    ]
