# Generated by Django 2.2.2 on 2021-03-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20210317_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='visit_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
