# Generated by Django 2.2.2 on 2021-02-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20210206_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='order_latitude',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='calllog',
            name='order_longitude',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
