# Generated by Django 2.2.2 on 2021-02-06 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210110_0935'),
        ('account', '0021_auto_20210206_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='fk_store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Store'),
        ),
    ]
