# Generated by Django 2.2.2 on 2021-03-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20210328_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='emergency_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
