# Generated by Django 2.2.2 on 2021-04-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20210328_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='visittype',
            name='slug',
            field=models.SlugField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
