# Generated by Django 2.0 on 2020-05-18 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0002_auto_20200518_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='send_from',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='send_to',
        ),
        migrations.RemoveField(
            model_name='message',
            name='inquiry',
        ),
        migrations.AddField(
            model_name='message',
            name='fk_message_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_message', to='inquiry.Message'),
        ),
        migrations.DeleteModel(
            name='Inquiry',
        ),
    ]
