# Generated by Django 2.2.2 on 2021-02-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_variationbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='variationbatch',
            name='use_batch',
            field=models.BooleanField(default=True),
        ),
    ]
