# Generated by Django 2.2.2 on 2021-02-28 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('products', '0003_variationbatch_use_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='variationbatch',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variationbatch',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.CreateModel(
            name='VariationPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('fk_user_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserType')),
                ('fk_variation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Variation')),
            ],
        ),
        migrations.CreateModel(
            name='VariationBatchPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('fk_variation_batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.VariationBatch')),
            ],
        ),
    ]
