# Generated by Django 2.2.2 on 2021-03-01 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('products', '0004_auto_20210228_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='variationbatchprice',
            name='fk_user_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserType'),
        ),
    ]
