# Generated by Django 2.2.2 on 2020-06-13 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wsc', '0001_initial'),
        ('store', '0001_initial'),
        ('products', '0006_auto_20200528_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fk_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Store'),
        ),
        migrations.AddField(
            model_name='product',
            name='fk_wsc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wsc.WaterSupplyCompany'),
        ),
    ]
