# Generated by Django 2.2.2 on 2021-03-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210301_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='variationbatch',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
