# Generated by Django 2.2.2 on 2020-06-13 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200613_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCommon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='fk_common_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductCommon'),
        ),
    ]
