# Generated by Django 2.2.2 on 2021-03-15 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_purchase_bill_number'),
        ('products', '0008_variationbatch_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='variationbatch',
            name='fk_purchaseitem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.PurchaseItem'),
        ),
    ]
