# Generated by Django 2.2.2 on 2020-08-10 16:39

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200613_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcommon',
            name='lab_report_file',
            field=models.FileField(blank=True, null=True, upload_to=products.models.common_product_lab_report_upload_to),
        ),
    ]
