# Generated by Django 2.2.2 on 2020-08-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productcommon_lab_report_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='can_sell_everywhere',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
