# Generated by Django 2.2.2 on 2021-03-16 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_variationbatch_fk_purchaseitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='is_internal',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='is_refill',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='keep_stock',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='price',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='sale_price',
        ),
        migrations.AddField(
            model_name='variation',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Brand'),
        ),
        migrations.AddField(
            model_name='variation',
            name='categories',
            field=models.ManyToManyField(blank=True, to='products.Category'),
        ),
        migrations.AddField(
            model_name='variation',
            name='code',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Company'),
        ),
        migrations.AddField(
            model_name='variation',
            name='generic_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.GenericName'),
        ),
        migrations.AddField(
            model_name='variation',
            name='rack_number',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
