# Generated by Django 2.2.2 on 2021-03-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210316_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='alert_expiry_days',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=20),
        ),
        migrations.AddField(
            model_name='variation',
            name='alert_quantity',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=20),
        ),
    ]
