# Generated by Django 2.2.2 on 2021-03-23 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
        ('products', '0011_auto_20210319_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='fk_counter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='counter.Counter'),
        ),
    ]
