# Generated by Django 2.2.2 on 2021-01-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_uservariationquantityhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='is_refill',
            field=models.BooleanField(default=False),
        ),
    ]
