# Generated by Django 2.2.2 on 2021-03-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_variation_fk_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='alert_expiry_days',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='alert_quantity',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=20, null=True),
        ),
    ]
