# Generated by Django 2.2.2 on 2021-01-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_variation_is_refill'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservariationquantityhistory',
            name='num_delta',
            field=models.FloatField(default=0),
        ),
    ]
