# Generated by Django 2.2.2 on 2021-04-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20210323_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='variationbatch',
            name='is_initial',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
