# Generated by Django 2.2.2 on 2021-01-10 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_uservariationquantityhistory_num_delta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservariationquantityhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jar_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
