# Generated by Django 2.2.2 on 2021-01-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20210110_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_internal',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='variation',
            name='is_internal',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
