# Generated by Django 2.2.2 on 2021-01-12 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20210112_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservariationquantityhistory',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='uservariationquantityhistory',
            name='timestamp',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
