# Generated by Django 2.0 on 2020-05-14 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='usertype',
            name='user_type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserTypes'),
        ),
    ]
