# Generated by Django 2.0 on 2020-05-16 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200514_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='user_type',
            field=models.OneToOneField(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserTypes'),
        ),
    ]
