# Generated by Django 2.2.2 on 2020-06-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
