# Generated by Django 2.2.2 on 2020-06-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.IntegerField(null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('slider_file', models.FileField(upload_to='slider_images')),
                ('upload_date', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
    ]
