# Generated by Django 2.0 on 2020-05-13 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.IntegerField(null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('fk_member_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_member_user', to=settings.AUTH_USER_MODEL)),
                ('fk_membership_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_member_user', to='membership.MembershipType')),
            ],
        ),
    ]
