# Generated by Django 2.0 on 2020-05-27 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_usermembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermembership',
            name='fk_member_user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_member_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='fk_membership_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_membership_type', to='membership.MembershipType'),
        ),
    ]
