# Generated by Django 2.2.2 on 2020-05-31 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_auto_20200522_2157'),
        ('membership', '0003_auto_20200527_1815'),
    ]

    operations = [
    ]
