# Generated by Django 2.2.2 on 2020-06-29 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200613_1711'),
        ('membership', '0004_merge_20200531_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermembership',
            name='auto_order_duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='is_auto_order',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='UserMembershipAutoOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('fk_usermembership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.UserMembership')),
                ('fk_variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Variation')),
            ],
        ),
    ]
