# Generated by Django 2.2.2 on 2021-02-21 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '__first__'),
        ('carts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreWiseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_total_price', models.DecimalField(decimal_places=2, default=5.99, max_digits=50)),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=50)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('grand_total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('order_id', models.CharField(blank=True, max_length=20, null=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_transit', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('order_latitude', models.CharField(blank=True, max_length=200, null=True)),
                ('order_longitude', models.CharField(blank=True, max_length=200, null=True)),
                ('is_auto_order', models.IntegerField(default=0)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.Cart')),
                ('fk_auth_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fk_delivery_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_delivery_user_storewiseorder', to=settings.AUTH_USER_MODEL)),
                ('fk_ordered_by_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_ordered_by_store_storewiseorder', to='store.Store')),
                ('fk_ordered_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_ordered_store_storewiseorder', to='store.Store')),
                ('fk_payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_ordered_store_storewiseorder', to='payment.PaymentMethod')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('refunded', 'Refunded')], default='created', max_length=120)),
                ('shipping_total_price', models.DecimalField(decimal_places=2, default=5.99, max_digits=50)),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=50)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('grand_total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('order_id', models.CharField(blank=True, max_length=20, null=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('order_latitude', models.CharField(blank=True, max_length=200, null=True)),
                ('order_longitude', models.CharField(blank=True, max_length=200, null=True)),
                ('is_auto_order', models.IntegerField(default=0)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.Cart')),
                ('fk_auth_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fk_delivery_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_delivery_user', to=settings.AUTH_USER_MODEL)),
                ('fk_ordered_by_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_ordered_by_store', to='store.Store')),
                ('fk_ordered_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_ordered_store', to='store.Store')),
                ('fk_payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_ordered_store', to='payment.PaymentMethod')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
