# Generated by Django 2.2.2 on 2021-03-13 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('products', '0008_variationbatch_purchase_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendor', '0002_auto_20210312_1844'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('tax_percentage', models.DecimalField(decimal_places=5, default=0.085, max_digits=10)),
                ('tax_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('active', models.BooleanField(default=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=25, null=True)),
                ('debit', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=25, null=True)),
                ('grand_total', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=25, null=True)),
                ('fk_payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.PaymentMethod')),
                ('fk_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.Vendor')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=25)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('line_item_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('orginal_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('ordered_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('is_return', models.BooleanField(blank=True, default=False, null=True)),
                ('fk_variation_batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.VariationBatch')),
                ('purchase', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Purchase')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchaseitems',
            field=models.ManyToManyField(related_name='purchaseitems', to='orders.PurchaseItem'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
