# Generated by Django 2.2.2 on 2021-03-13 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_variationbatch_purchase_date'),
        ('orders', '0002_auto_20210313_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='fk_variation_batch',
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='fk_variation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Variation'),
        ),
    ]
