# Generated by Django 2.2.2 on 2021-03-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210313_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='line_item_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
