# Generated by Django 2.2.2 on 2020-06-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200602_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_latitude',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_longitude',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
