# Generated by Django 2.2.2 on 2021-03-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210313_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='batchno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=25),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='free_quantity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=25),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=25),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='total_quantity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=25),
        ),
    ]
