# Generated by Django 2.2.2 on 2021-03-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20210314_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
