# Generated by Django 2.2.2 on 2021-03-14 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_variationbatch_purchase_date'),
        ('orders', '0008_purchaseitem_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='fk_product_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductUnit'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='packaging_quantity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=25),
        ),
    ]
