# Generated by Django 2.2.2 on 2020-06-17 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200613_1735'),
        ('payment', '0001_initial'),
        ('carts', '0006_auto_20200602_2231'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0008_order_fk_ordered_by_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreWiseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_total_price', models.DecimalField(decimal_places=2, default=5.99, max_digits=50)),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=50)),
                ('order_id', models.CharField(blank=True, max_length=20, null=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('order_latitude', models.CharField(blank=True, max_length=200, null=True)),
                ('order_longitude', models.CharField(blank=True, max_length=200, null=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.Cart')),
                ('fk_auth_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fk_delivery_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_delivery_user_storewiseorder', to=settings.AUTH_USER_MODEL)),
                ('fk_ordered_by_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_ordered_by_store_storewiseorder', to='store.Store')),
                ('fk_ordered_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_ordered_store_storewiseorder', to='store.Store')),
                ('fk_payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_ordered_store_storewiseorder', to='payment.PaymentMethod')),
            ],
        ),
    ]
