# Generated by Django 2.2.2 on 2020-06-21 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_auto_20200622_0021'),
        ('orders', '0009_storewiseorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='storewiseorder',
            name='fk_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_route_storewiseorder', to='routes.Route'),
        ),
    ]
