# Generated by Django 2.2.2 on 2020-07-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_storewiseorder_fk_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='storewiseorder',
            name='is_transit',
            field=models.BooleanField(default=False),
        ),
    ]
