# Generated by Django 2.2.2 on 2021-03-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20210315_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='bill_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
