# Generated by Django 2.2.2 on 2021-03-26 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20210323_2243'),
        ('orders', '0011_purchase_bill_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_quantity', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('change_quantity', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('final_quantity', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fk_purchaseitem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.PurchaseItem')),
                ('fk_variation_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.VariationBatch')),
            ],
        ),
    ]
