# Generated by Django 2.2.2 on 2021-03-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_adjustment_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adjustment',
            name='fk_purchaseitem',
        ),
        migrations.AddField(
            model_name='adjustment',
            name='operation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
