# Generated by Django 2.2.2 on 2020-08-10 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20200808_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storewiseorder',
            options={'ordering': ['-id']},
        ),
    ]
