# Generated by Django 2.2.2 on 2021-01-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20200810_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_auto_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='storewiseorder',
            name='is_auto_order',
            field=models.IntegerField(default=0),
        ),
    ]
