# Generated by Django 2.2.2 on 2021-02-23 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('group', models.IntegerField(blank=True, null=True)),
                ('key', models.CharField(blank=True, max_length=100)),
                ('value', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SideMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.FloatField(null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_settings.SideMenu')),
            ],
        ),
    ]
