# Generated by Django 2.2.2 on 2020-11-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('group', models.IntegerField(blank=True, null=True)),
                ('key', models.CharField(blank=True, max_length=100)),
                ('value', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
