# Generated by Django 2.2.2 on 2021-02-21 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='Prescription')),
                ('name', models.CharField(max_length=100)),
                ('version', models.IntegerField(default=0)),
                ('upload_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('doctor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('hospital_name', models.CharField(blank=True, max_length=200, null=True)),
                ('size', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
