# Generated by Django 2.2.2 on 2020-06-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0002_auto_20200608_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='file',
            field=models.FileField(upload_to='Prescription'),
        ),
    ]
