# Generated by Django 2.2.2 on 2020-06-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_auto_20200622_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routedetail',
            name='order_latitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='routedetail',
            name='order_longitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
    ]
